import AppKit
import SwiftUI

// The source of truth for the packaged icon and the SVG/PNG previews.
// Legacy .icns consumers need the silhouette and transparent margins in the
// artwork itself. Menu-bar and in-app glyphs live separately in BrandViews.swift.
struct IconArtwork {
    let background: CGPath
    let mark: CGPath

    init(pointSize: Int) {
        background = RoundedRectangle(cornerRadius: 184, style: .continuous)
            .path(in: CGRect(x: 100, y: 100, width: 824, height: 824)).cgPath

        let compact = pointSize <= 16
        let small = pointSize <= 32
        let outerRadius: CGFloat = compact ? 88 : 78
        let innerRadius: CGFloat = compact ? 30 : (small ? 40 : 46)
        let dotRadius: CGFloat = compact ? 28 : (small ? 20 : 18)
        let coreSize: CGFloat = compact ? 84 : (small ? 72 : 68)
        let path = CGMutablePath()

        func circle(_ x: CGFloat, _ y: CGFloat, _ radius: CGFloat) {
            path.addEllipse(in: CGRect(x: x - radius, y: y - radius,
                                       width: radius * 2, height: radius * 2))
        }
        for (x, y): (CGFloat, CGFloat) in [(302, 322), (722, 322), (512, 742)] {
            circle(x, y, outerRadius)
            circle(x, y, innerRadius)
        }
        // At 16 pt, one clear beat per connection survives both 1x and Retina
        // rendering better than two subpixel dots. Larger icons retain both.
        let dots: [(CGFloat, CGFloat)] = compact
            ? [(410, 420), (614, 420), (512, 618)]
            : [(434, 442), (385, 397), (590, 442), (639, 397), (512, 590), (512, 638)]
        for (x, y) in dots { circle(x, y, dotRadius) }

        let core = CGPath(roundedRect: CGRect(x: -coreSize / 2, y: -coreSize / 2,
                                              width: coreSize, height: coreSize),
                          cornerWidth: coreSize / 4, cornerHeight: coreSize / 4,
                          transform: nil)
        let transform = CGAffineTransform(translationX: 512, y: 512).rotated(by: .pi / 4)
        path.addPath(core, transform: transform)
        mark = path
    }

    func png(pixelSize: Int) throws -> Data {
        let colorSpace = CGColorSpace(name: CGColorSpace.sRGB)!
        guard let context = CGContext(data: nil, width: pixelSize, height: pixelSize,
                                      bitsPerComponent: 8, bytesPerRow: pixelSize * 4,
                                      space: colorSpace,
                                      bitmapInfo: CGImageAlphaInfo.premultipliedLast.rawValue) else {
            throw IconError.message("Unable to create the icon drawing context.")
        }
        context.clear(CGRect(x: 0, y: 0, width: pixelSize, height: pixelSize))
        context.translateBy(x: 0, y: CGFloat(pixelSize))
        context.scaleBy(x: CGFloat(pixelSize) / 1024, y: -CGFloat(pixelSize) / 1024)
        context.setFillColor(CGColor(colorSpace: colorSpace,
                                     components: [CGFloat(21) / 255, CGFloat(24) / 255, CGFloat(22) / 255, 1])!)
        context.addPath(background)
        context.fillPath()
        context.setFillColor(CGColor(colorSpace: colorSpace,
                                     components: [CGFloat(53) / 255, CGFloat(220) / 255, CGFloat(122) / 255, 1])!)
        context.addPath(mark)
        context.drawPath(using: .eoFill)
        guard let image = context.makeImage(),
              let data = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:]) else {
            throw IconError.message("Unable to encode the icon PNG.")
        }
        return data
    }

    var svg: String {
        """
        <?xml version="1.0" encoding="UTF-8"?>
        <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024" role="img" aria-labelledby="title desc">
          <title id="title">Codex Bridge app icon</title>
          <desc id="desc">A central orchestration core coordinating three independent project nodes.</desc>
          <!-- Generated by macos/generate-app-icons.swift. Exterior pixels stay transparent for legacy macOS icon consumers. -->
          <path fill="#151816" d="\(background.svgPath)"/>
          <path fill="#35DC7A" fill-rule="evenodd" d="\(mark.svgPath)"/>
        </svg>

        """
    }
}

extension CGPath {
    var svgPath: String {
        var commands: [String] = []
        func point(_ value: CGPoint) -> String {
            String(format: "%.3f %.3f", locale: Locale(identifier: "en_US_POSIX"),
                   Double(value.x), Double(value.y))
        }
        applyWithBlock { element in
            let value = element.pointee
            switch value.type {
            case .moveToPoint: commands.append("M\(point(value.points[0]))")
            case .addLineToPoint: commands.append("L\(point(value.points[0]))")
            case .addQuadCurveToPoint:
                commands.append("Q\(point(value.points[0])) \(point(value.points[1]))")
            case .addCurveToPoint:
                commands.append("C\(point(value.points[0])) \(point(value.points[1])) \(point(value.points[2]))")
            case .closeSubpath: commands.append("Z")
            @unknown default: preconditionFailure("Unexpected icon path element")
            }
        }
        return commands.joined(separator: " ")
    }
}

enum IconError: Error, CustomStringConvertible {
    case message(String)
    var description: String {
        switch self { case .message(let message): return message }
    }
}

// Validate the exported pixels, not just the presence of an alpha channel.
// This runs during every app build, before the PNGs are packed into .icns.
func validate(_ data: Data, pixelSize: Int) throws {
    guard let image = NSBitmapImageRep(data: data), image.hasAlpha,
          image.pixelsWide == pixelSize, image.pixelsHigh == pixelSize else {
        throw IconError.message("Invalid \(pixelSize)px icon dimensions or alpha channel.")
    }
    for coordinate in 0..<pixelSize {
        for (x, y) in [(coordinate, 0), (coordinate, pixelSize - 1),
                       (0, coordinate), (pixelSize - 1, coordinate)] {
            guard image.colorAt(x: x, y: y)?.alphaComponent == 0 else {
                throw IconError.message("The \(pixelSize)px icon lost its transparent exterior.")
            }
        }
    }
    // Stay outside the antialiased contour even in the 16 px representation.
    let corner = max(0, pixelSize / 8 - 1)
    let cornerAlpha = image.colorAt(x: corner, y: corner)?.alphaComponent ?? 1
    let centerAlpha = image.colorAt(x: pixelSize / 2, y: pixelSize / 2)?.alphaComponent ?? 0
    guard cornerAlpha == 0, centerAlpha == 1 else {
        throw IconError.message("The \(pixelSize)px icon lost its rounded silhouette or visible center (corner alpha: \(cornerAlpha), center alpha: \(centerAlpha)).")
    }
}

do {
    var iconset: URL?
    var previews: URL?
    var arguments = CommandLine.arguments.dropFirst()[...]
    while let argument = arguments.popFirst() {
        guard let value = arguments.popFirst() else {
            throw IconError.message("Missing value for \(argument).")
        }
        switch argument {
        case "--iconset": iconset = URL(fileURLWithPath: value, isDirectory: true)
        case "--preview-directory": previews = URL(fileURLWithPath: value, isDirectory: true)
        default: throw IconError.message("Unknown option: \(argument).")
        }
    }
    guard let iconset, iconset.pathExtension == "iconset" else {
        throw IconError.message("Usage: swift generate-app-icons.swift --iconset <AppIcon.iconset> [--preview-directory <directory>]")
    }
    try FileManager.default.createDirectory(at: iconset, withIntermediateDirectories: true)
    for points in [16, 32, 128, 256, 512] {
        for scale in [1, 2] {
            let pixels = points * scale
            let data = try IconArtwork(pointSize: points).png(pixelSize: pixels)
            try validate(data, pixelSize: pixels)
            let suffix = scale == 2 ? "@2x" : ""
            try data.write(to: iconset.appendingPathComponent("icon_\(points)x\(points)\(suffix).png"), options: .atomic)
        }
    }
    if let previews {
        try FileManager.default.createDirectory(at: previews, withIntermediateDirectories: true)
        let artwork = IconArtwork(pointSize: 512)
        try artwork.png(pixelSize: 1024).write(to: previews.appendingPathComponent("app-icon-1024.png"), options: .atomic)
        try Data(artwork.svg.utf8).write(to: previews.appendingPathComponent("app-icon.svg"), options: .atomic)
    }
    print("Generated and validated 10 macOS icon variants: \(iconset.path)")
} catch {
    FileHandle.standardError.write(Data("\(error)\n".utf8))
    exit(1)
}
