import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { serializedUiTranslations } from "./uiI18n.js";
import { PRODUCT_INFO } from "./productInfo.js";

export const ACTIVITY_CARD_URI = `ui://${PRODUCT_INFO.runtimeName}/activity-v1.html`;
export const ACTIVITY_CARD_MIME_TYPE = "text/html;profile=mcp-app";

export function registerActivityCardResource(server: McpServer): void {
  server.registerResource(
    "codex-activity-card",
    ACTIVITY_CARD_URI,
    {
      title: `${PRODUCT_INFO.displayName} Activity Manager`,
      description: "Localized live Activity view for Codex work in the current conversation.",
      mimeType: ACTIVITY_CARD_MIME_TYPE
    },
    async () => ({
      contents: [
        {
          uri: ACTIVITY_CARD_URI,
          mimeType: ACTIVITY_CARD_MIME_TYPE,
          text: ACTIVITY_CARD_HTML,
          _meta: {
            ui: {
              prefersBorder: true,
              csp: { connectDomains: [], resourceDomains: [] },
              domain: "https://web-sandbox.oaiusercontent.com"
            },
            "openai/widgetDescription":
              "Shows current GPT–Codex Activities, jobs, progress, verification state, and force-stop controls.",
            "openai/widgetPrefersBorder": true,
            "openai/widgetCSP": { connect_domains: [], resource_domains: [] },
            "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com"
          }
        }
      ]
    })
  );
}

export const ACTIVITY_CARD_HTML = String.raw`<!doctype html>
<html lang="en" dir="auto">
<head>
  <meta charset="utf-8" /><meta name="viewport" content="width=device-width,initial-scale=1" />
  <title>Codex activities</title>
  <style>
    :root{color-scheme:light dark;font-family:ui-sans-serif,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;--surface:color-mix(in srgb,Canvas 96%,CanvasText 4%);--muted:color-mix(in srgb,CanvasText 62%,transparent);--border:color-mix(in srgb,CanvasText 16%,transparent);--accent:#1777ff;--danger:#c34132;--warn:#b87503;--ok:#1a8f55}*{box-sizing:border-box}body{margin:0;padding:12px;background:transparent;color:CanvasText}.card{border:1px solid var(--border);border-radius:16px;background:var(--surface);padding:14px}header{display:flex;align-items:center;justify-content:space-between;gap:10px}h1{margin:0;font-size:18px}.counts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px;margin:12px 0}.count{border:1px solid var(--border);border-radius:10px;padding:8px}.count b{display:block;font-size:17px}.count span,.meta,.empty,.message{font-size:11px;color:var(--muted)}#activities{display:grid;gap:9px}.activity{border:1px solid var(--border);border-radius:12px;padding:11px}.activity-head{display:flex;align-items:start;justify-content:space-between;gap:8px}.activity h2{font-size:14px;margin:0}.badges{display:flex;flex-wrap:wrap;gap:5px;margin-top:6px}.badge{font-size:10px;border:1px solid var(--border);border-radius:999px;padding:2px 7px}.badge.bad{color:var(--danger)}.badge.warn{color:var(--warn)}.badge.ok{color:var(--ok)}details{margin-top:8px}summary{cursor:pointer;font-size:11px;color:var(--accent)}.job{border-top:1px solid var(--border);padding:8px 0;display:grid;gap:6px}.job:first-child{margin-top:6px}.job-row{display:flex;align-items:center;justify-content:space-between;gap:8px}.mono{font-family:ui-monospace,SFMono-Regular,Menlo,monospace;font-size:10px;word-break:break-all}.actions{display:flex;gap:6px;flex-wrap:wrap}.panel{border:1px solid var(--border);border-radius:9px;padding:8px;display:grid;gap:6px}.event{font-size:10px;line-height:1.4;border-left:2px solid var(--border);padding-left:7px;overflow-wrap:anywhere}input,textarea,select{width:100%;border:1px solid var(--border);border-radius:8px;background:Canvas;color:CanvasText;padding:7px;font:inherit;font-size:11px}textarea{min-height:58px;resize:vertical}button{border:1px solid var(--border);border-radius:9px;background:Canvas;color:CanvasText;padding:6px 9px;font-size:11px;font-weight:650;cursor:pointer}button.danger{color:var(--danger);border-color:color-mix(in srgb,var(--danger) 45%,transparent)}button:disabled{opacity:.55;cursor:wait}.footer{display:flex;justify-content:space-between;align-items:center;gap:8px;margin-top:10px}.message.error{color:var(--danger)}@media(max-width:520px){.counts{grid-template-columns:repeat(2,minmax(0,1fr))}.activity-head{display:grid}}
  </style>
</head>
<body><main class="card"><header><h1 data-i18n="activity.title"></h1><button id="refresh" data-i18n="common.refresh"></button></header><section class="counts" id="counts"></section><section id="activities"></section><div class="footer"><span class="message" id="message" role="status" aria-live="polite"></span><span class="meta" id="updated"></span></div></main>
<script>
  const BUNDLES=${serializedUiTranslations()};const pending=new Map();let requestId=1,snapshot=null,mounted=true,watching=false,failures=0,handoffTimer=null;const initialMetadata=window.openai&&window.openai.toolResponseMetadata||{};let localeTag=String(window.openai&&window.openai.locale||initialMetadata["openai/locale"]||initialMetadata["webplus/i18n"]||navigator.language||"en"),locale=resolveLocale(localeTag),t=BUNDLES[locale]||BUNDLES.en;
  const activities=document.getElementById("activities"),counts=document.getElementById("counts"),message=document.getElementById("message"),updated=document.getElementById("updated"),refresh=document.getElementById("refresh");
  function resolveLocale(value){const v=String(value||"en").replaceAll("_","-").toLowerCase();if(v==="ko"||v.startsWith("ko-"))return"ko";if(v==="ja"||v.startsWith("ja-"))return"ja";if(v==="zh-hant"||/^zh-(tw|hk|mo)(-|$)/.test(v))return"zh-Hant";if(v==="zh"||v==="zh-hans"||v.startsWith("zh-"))return"zh-Hans";for(const key of["es","fr","de","pt"])if(v===key||v.startsWith(key+"-"))return key;return"en"}
  function setLocale(value){localeTag=String(value||"en").replaceAll("_","-");locale=resolveLocale(localeTag);t=BUNDLES[locale]||BUNDLES.en;document.documentElement.lang=localeTag;for(const node of document.querySelectorAll("[data-i18n]"))node.textContent=t[node.dataset.i18n]||BUNDLES.en[node.dataset.i18n];refresh.setAttribute("aria-label",t["common.refresh"]);if(snapshot)render(snapshot)}
  function rpcRequest(method,params,timeout=70000){return new Promise((resolve,reject)=>{const id=requestId++,timer=setTimeout(()=>{pending.delete(id);reject(new Error(t["common.error"]))},timeout);pending.set(id,{resolve:(v)=>{clearTimeout(timer);resolve(v)},reject:(e)=>{clearTimeout(timer);reject(e)}});window.parent.postMessage({jsonrpc:"2.0",id,method,params},"*")})}
  function callTool(name,args,timeout=70000){if(window.openai&&typeof window.openai.callTool==="function")return window.openai.callTool(name,args);return rpcRequest("tools/call",{name,arguments:args},timeout)}
  function unwrap(result){if(result&&result._meta){const responseLocale=result._meta["openai/locale"]||result._meta["webplus/i18n"];if(responseLocale)setLocale(responseLocale)}if(result&&result.isError){const entry=Array.isArray(result.content)&&result.content.find((item)=>item&&item.type==="text");throw new Error(entry&&entry.text||t["common.error"])}const data=result&&result.structuredContent||result;if(data&&typeof data==="object"&&result&&result._meta&&result._meta.activityDetails)return Object.assign({},data,{__private:result._meta.activityDetails});return data}
  function node(tag,className,text){const el=document.createElement(tag);if(className)el.className=className;if(text!==undefined)el.textContent=text;return el}
  function badge(text,kind){return node("span","badge "+(kind||""),text)}
  function codeLabel(group,value){return t[group+"."+value]||String(value||"")}
  function isActive(status){return status==="running"||status==="terminating"||status==="termination-failed"}
  function statusClass(status){return status==="completed"||status==="verified"?"ok":status==="running"?"":status==="terminating"?"warn":"bad"}
  function render(next){if(!next||!Array.isArray(next.activities))return;snapshot=next;counts.replaceChildren();const a=next.aggregates||{};for(const item of [["activity.running",a.running||0],["activity.attention",a.needsAttention||0],["activity.verification",a.readyForVerification||0],["activity.failed",a.failed||0]]){const box=node("div","count");box.append(node("b","",String(item[1])),node("span","",t[item[0]]));counts.appendChild(box)}activities.replaceChildren();if(next.activities.length===0)activities.appendChild(node("p","empty",t["activity.empty"]));for(const item of next.activities)activities.appendChild(renderActivity(item));updated.textContent=t["activity.updated"]+": "+new Date(next.generatedAt).toLocaleTimeString(localeTag);message.textContent="";message.classList.remove("error");scheduleHandoffs();if(!watching)void watch()}
  function renderActivity(item){const box=node("article","activity"),head=node("div","activity-head"),left=node("div"),title=node("h2","",item.title),badges=node("div","badges");badges.append(badge(codeLabel("kind",item.kind)),badge(codeLabel("lifecycle",item.lifecycle),statusClass(item.lifecycle)),badge(codeLabel("waiting",item.waitingOn)),badge(codeLabel("verification",item.verification),statusClass(item.verification)));left.append(title,badges);const actions=node("div","actions");if((item.jobs||[]).some((job)=>isActive(job.status))){const stop=node("button","danger",t["activity.forceStop"]);stop.setAttribute("aria-label",t["activity.forceStop"]+" "+item.title);stop.addEventListener("click",()=>forceActivity(item,stop));actions.appendChild(stop)}head.append(left,actions);box.appendChild(head);const meta=node("div","meta",(item.counts&&item.counts.total||0)+" "+t["activity.jobs"]+" · "+(item.threadCount||0)+" "+t["activity.threads"]);box.appendChild(meta);if(item.lifecycle==="terminating")box.appendChild(node("p","message",t["activity.terminating"]));const detail=document.createElement("details"),summary=document.createElement("summary");summary.textContent=t["activity.viewDetails"];detail.addEventListener("toggle",()=>summary.textContent=detail.open?t["activity.hideDetails"]:t["activity.viewDetails"]);detail.appendChild(summary);for(const job of item.jobs||[])detail.appendChild(renderJob(item,job));box.appendChild(detail);return box}
  function privateJob(jobId){for(const activity of snapshot&&snapshot.__private&&snapshot.__private.activities||[]){const found=(activity.jobs||[]).find((job)=>job.jobId===jobId);if(found)return found}return null}
  function renderJob(activity,job){const box=node("div","job"),row=node("div","job-row"),left=node("div"),details=privateJob(job.jobId)||{};left.append(node("div","mono",(job.threadId||job.jobId)),badge(codeLabel("job",job.status),statusClass(job.status)));row.appendChild(left);if(isActive(job.status)){const stop=node("button","danger",t["activity.forceStop"]);stop.setAttribute("aria-label",t["activity.forceStop"]+" "+job.jobId);stop.addEventListener("click",()=>forceJob(job,stop));row.appendChild(stop)}box.append(row,node("div","meta",(job.operation||"")+" · "+(job.backendKind||"")+" · "+(job.workingDirectory||"")));if(job.health==="no-progress-observed")box.appendChild(node("div","message",t["activity.noSignal"]));if(job.health==="orphaned")box.appendChild(node("div","message error",t["activity.orphaned"]));if(job.health==="worker-lost")box.appendChild(node("div","message error",t["activity.workerLost"]));if(job.status==="terminating")box.appendChild(node("div","message",t["activity.terminating"]));if(job.status==="termination-failed")box.appendChild(node("div","message error",t["activity.terminationFailed"]));if(job.error)box.appendChild(node("div","message error",job.error));for(const interaction of details.pendingInteractions||[])box.appendChild(renderInteraction(activity,job,interaction));if(job.canSteer)box.appendChild(renderSteering(activity,job));const events=node("div","panel"),eventsTitle=node("strong","",t["activity.events"]),list=(details.publicEvents||[]).slice(-20);events.appendChild(eventsTitle);if(list.length===0)events.appendChild(node("div","message",t["activity.noEvents"]));for(const event of list)events.appendChild(node("div","event",new Date(event.createdAt).toLocaleTimeString(localeTag)+" · "+event.type+"/"+event.phase+" · "+event.summary));box.appendChild(events);return box}
  function renderInteraction(activity,job,interaction){const panel=node("div","panel"),title=node("strong","",interaction.kind==="user-input"?t["activity.inputRequired"]:t["activity.approval"]);panel.append(title,node("div","message",interaction.summary));if(interaction.kind!=="user-input"){const actions=node("div","actions"),approve=node("button","",t["activity.approve"]),decline=node("button","",t["activity.decline"]);approve.addEventListener("click",()=>respondInteraction(activity,job,interaction,{interactionDecision:"accept"},approve));decline.addEventListener("click",()=>respondInteraction(activity,job,interaction,{interactionDecision:"decline"},decline));actions.append(approve,decline);panel.appendChild(actions);return panel}const fields=[];for(const question of interaction.questions||[]){const input=document.createElement("input"),inputId="input-"+interaction.interactionId+"-"+question.id,label=node("label","message",question.question);input.id=inputId;label.htmlFor=inputId;input.type=question.isSecret?"password":"text";input.autocomplete="off";input.dataset.questionId=question.id;panel.appendChild(label);if(question.options&&question.options.length){const listId="options-"+interaction.interactionId+"-"+question.id,list=document.createElement("datalist");list.id=listId;for(const choice of question.options){const option=document.createElement("option");option.value=choice.label;option.label=choice.description||choice.label;list.appendChild(option)}input.setAttribute("list",listId);panel.appendChild(list)}panel.appendChild(input);fields.push(input)}const send=node("button","",t["activity.answer"]);send.addEventListener("click",()=>{const answers={};for(const field of fields)answers[field.dataset.questionId]=[field.value];void respondInteraction(activity,job,interaction,{interactionAnswers:answers},send)});panel.appendChild(send);return panel}
  function renderSteering(activity,job){const panel=node("div","panel"),input=document.createElement("textarea"),send=node("button","",t["activity.steer"]);input.placeholder=t["activity.steerPlaceholder"];input.setAttribute("aria-label",t["activity.steer"]);send.addEventListener("click",async()=>{const prompt=input.value.trim();if(!prompt)return;send.disabled=true;try{await callTool("codex_activity_update",{activityId:activity.activityId,action:"steer",jobId:job.jobId,expectedJobVersion:job.version,steeringPrompt:prompt});input.value="";await reload()}catch(error){message.textContent=String(error&&error.message||error);message.classList.add("error");send.disabled=false}});panel.append(input,send);return panel}
  async function respondInteraction(activity,job,interaction,response,button){button.disabled=true;try{await callTool("codex_activity_update",Object.assign({activityId:activity.activityId,action:"respond-interaction",jobId:job.jobId,expectedJobVersion:job.version,interactionId:interaction.interactionId},response));await reload()}catch(error){message.textContent=String(error&&error.message||error);message.classList.add("error");button.disabled=false}}
  async function forceActivity(item,button){if(!confirm(t["activity.forceConfirmTitle"]+"\n\n"+t["activity.forceConfirm"]+"\n"+t["activity.partialChanges"]))return;button.disabled=true;message.textContent=t["activity.forceStopping"];try{const affected=[...new Set((item.jobs||[]).flatMap((job)=>job.affectedJobIds||[job.jobId]))];await callTool("codex_activity_update",{activityId:item.activityId,expectedVersion:item.version,action:"cancel",acknowledgeAffectedJobIds:affected});message.textContent=t["activity.forceStopped"];await reload()}catch(error){message.textContent=String(error&&error.message||error);message.classList.add("error");button.disabled=false}}
  async function forceJob(job,button){if(!confirm(t["activity.forceConfirmTitle"]+"\n\n"+t["activity.forceConfirm"]+"\n"+t["activity.partialChanges"]))return;button.disabled=true;message.textContent=t["activity.forceStopping"];try{await callTool("codex_cancel",{jobId:job.jobId,expectedVersion:job.version,acknowledgeAffectedJobIds:job.affectedJobIds||[job.jobId]});message.textContent=t["activity.forceStopped"];await reload()}catch(error){message.textContent=String(error&&error.message||error);message.classList.add("error");button.disabled=false}}
  async function reload(){const next=unwrap(await callTool("codex_status",{activityView:true}));render(next)}
  async function watch(){if(!mounted||!snapshot||watching)return;watching=true;try{const next=unwrap(await callTool("codex_status",{activityView:true,afterVersion:snapshot.scopeVersion,waitFor:"change",waitMs:55000}));failures=0;watching=false;if(mounted)render(next)}catch(error){watching=false;if(!mounted)return;failures++;if(failures>=5){message.textContent=t["activity.manualRefresh"];message.classList.add("error");return}const jitter=Math.floor(Math.random()*750);setTimeout(()=>void watch(),Math.min(30000,1000*Math.pow(2,failures))+jitter)}}
  function scheduleHandoffs(){if(handoffTimer||!snapshot||snapshot.deliveryMode!=="auto-handoff"||!Array.isArray(snapshot.pendingHandoffs)||snapshot.pendingHandoffs.length===0)return;handoffTimer=setTimeout(()=>{handoffTimer=null;void dispatchHandoffs()},1500)}
  async function sendFollowUp(prompt){try{return await rpcRequest("ui/message",{role:"user",content:{type:"text",text:prompt}},10000)}catch(standardError){if(window.openai&&typeof window.openai.sendFollowUpMessage==="function")return window.openai.sendFollowUpMessage({prompt});throw standardError}}
  async function dispatchHandoffs(){let claimed=[];try{const claim=unwrap(await callTool("codex_activity_handoff",{action:"claim-batch",outboxIds:snapshot.pendingHandoffs.map((event)=>event.outboxId)}));claimed=claim&&Array.isArray(claim.events)?claim.events:[];if(claimed.length===0)return;const lookup=new Map(snapshot.pendingHandoffs.map((event)=>[event.outboxId,event])),ids=claimed.map((event)=>event.activityId),jobs=claimed.flatMap((event)=>lookup.get(event.outboxId)&&lookup.get(event.outboxId).jobIds||[]),outboxIds=claimed.map((event)=>event.outboxId);const prompt="Codex Activity completion handoff. origin="+claim.origin+"; handoffDepth="+claim.handoffDepth+"; handoffBatchId="+claim.handoffBatchId+". Activity IDs: "+ids.join(", ")+". Job IDs: "+jobs.join(", ")+". Retrieve authoritative results with codex_status/codex_activity. For verify activities, independently inspect requested files, git diff/status, tests, and artifacts before reporting completion or continuing the exact thread for corrections. For notify activities, summarize without inventing verification. Do not quote raw Codex output and do not create another automatic handoff from this handoff.";await sendFollowUp(prompt);await callTool("codex_activity_handoff",{action:"delivered-batch",outboxIds})}catch(error){if(claimed.length)await callTool("codex_activity_handoff",{action:"release-batch",outboxIds:claimed.map((event)=>event.outboxId)}).catch(()=>{});message.textContent=String(error&&error.message||error);message.classList.add("error")}}
  window.addEventListener("message",(event)=>{if(event.source!==window.parent)return;const m=event.data;if(!m||m.jsonrpc!=="2.0")return;if(m.id!==undefined&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(new Error(m.error.message||t["common.error"])):p.resolve(m.result);return}if(m.method==="ui/notifications/tool-result")render(unwrap(m.params))},{passive:true});
  window.addEventListener("openai:set_globals",(event)=>{const g=event.detail&&event.detail.globals,metadata=g&&g.toolResponseMetadata;const responseLocale=metadata&&(metadata["openai/locale"]||metadata["webplus/i18n"]);if(g&&g.locale)setLocale(g.locale);else if(responseLocale)setLocale(responseLocale);if(g&&g.toolOutput)render(Object.assign({},g.toolOutput,metadata&&metadata.activityDetails?{__private:metadata.activityDetails}:{}))});
  window.addEventListener("pagehide",()=>{mounted=false;watching=false;for(const [id,request] of pending){window.parent.postMessage({jsonrpc:"2.0",method:"notifications/cancelled",params:{requestId:id,reason:"Activity card unmounted"}},"*");request.reject(new Error("Activity card unmounted"))}pending.clear()});window.addEventListener("pageshow",()=>{mounted=true;if(snapshot&&!watching)void reload()});document.addEventListener("visibilitychange",()=>{if(document.visibilityState==="visible"){mounted=true;if(snapshot&&!watching)void reload()}});refresh.addEventListener("click",()=>reload().catch((error)=>{message.textContent=String(error&&error.message||error);message.classList.add("error")}));
  setLocale(localeTag);if(window.openai&&window.openai.toolOutput)render(Object.assign({},window.openai.toolOutput,window.openai.toolResponseMetadata&&window.openai.toolResponseMetadata.activityDetails?{__private:window.openai.toolResponseMetadata.activityDetails}:{}));else void reload().catch((error)=>{message.textContent=String(error&&error.message||error);message.classList.add("error")});
</script></body></html>`;
