const COPY = {
  "problem.reviewLabel": ["Problem review", "문제 확인 상태", "問題の確認状態", "问题查看状态", "問題查看狀態", "Revisión de problemas", "Vérification des problèmes", "Problemprüfung", "Revisão de problemas"],
  "problem.pending": ["Needs action", "처리 필요", "対応が必要", "待处理", "待處理", "Por resolver", "À traiter", "Handlungsbedarf", "Por resolver"],
  "problem.acknowledged": ["Reviewed history", "확인한 기록", "確認済みの履歴", "已查看记录", "已查看記錄", "Historial revisado", "Historique vérifié", "Bestätigter Verlauf", "Histórico revisto"],
  "problem.kindLabel": ["Problem type", "문제 유형", "問題の種類", "问题类型", "問題類型", "Tipo de problema", "Type de problème", "Problemtyp", "Tipo de problema"],
  "problem.kind.all": ["All types", "전체 유형", "すべての種類", "所有类型", "所有類型", "Todos los tipos", "Tous les types", "Alle Typen", "Todos os tipos"],
  "problem.kind.failed": ["Failed or interrupted", "실패·중단", "失敗・中断", "失败或中断", "失敗或中斷", "Fallos e interrupciones", "Échecs et interruptions", "Fehler und Unterbrechungen", "Falhas e interrupções"],
  "problem.kind.unknown": ["Status unavailable", "상태 확인 불가", "状態を確認できません", "无法确认状态", "無法確認狀態", "Estado no disponible", "État indisponible", "Status unbekannt", "Estado indisponível"],
  "problem.kind.termination-failed": ["Termination failed", "종료 실패", "終了失敗", "终止失败", "終止失敗", "Error al detener", "Échec de l’arrêt", "Beenden fehlgeschlagen", "Falha ao terminar"],
  "problem.kind.orphaned": ["Connection lost", "연결 끊김", "接続切断", "连接中断", "連線中斷", "Conexión perdida", "Connexion perdue", "Verbindung verloren", "Ligação perdida"],
  "problem.ackAll": ["Review all finished failures", "종료된 실패 모두 확인", "終了済みの失敗をすべて確認", "查看所有已结束的失败", "查看所有已結束的失敗", "Revisar todos los fallos finalizados", "Vérifier tous les échecs terminés", "Alle beendeten Fehler bestätigen", "Rever todas as falhas terminadas"],
  "problem.ackSelected": ["Review selected failures", "선택한 실패 확인", "選択した失敗を確認", "查看所选失败", "查看所選失敗", "Revisar fallos seleccionados", "Vérifier les échecs sélectionnés", "Ausgewählte Fehler bestätigen", "Rever falhas selecionadas"],
  "problem.select": ["Select failure for {name}", "{name}의 실패 선택", "{name}の失敗を選択", "选择{name}的失败", "選擇{name}的失敗", "Seleccionar fallo de {name}", "Sélectionner l’échec de {name}", "Fehler von {name} auswählen", "Selecionar falha de {name}"],
  "problem.selectShort": ["Select", "선택", "選択", "选择", "選擇", "Seleccionar", "Sélectionner", "Auswählen", "Selecionar"],
  "problem.undo": ["Undo review", "확인 취소", "確認を取り消す", "撤销查看", "撤銷查看", "Deshacer revisión", "Annuler la vérification", "Bestätigung zurücknehmen", "Anular revisão"],
  "problem.recheck": ["Check status again", "상태 다시 확인", "状態を再確認", "重新确认状态", "重新確認狀態", "Volver a comprobar estado", "Revérifier l’état", "Status erneut prüfen", "Verificar estado novamente"],
  "problem.retryStop": ["Retry termination", "종료 재시도", "終了を再試行", "重试终止", "重試終止", "Reintentar detención", "Réessayer l’arrêt", "Beenden erneut versuchen", "Tentar terminar novamente"],
  "problem.noDetails": ["Detailed error information for this earlier run is no longer retained.", "이전 실행의 상세 오류 정보는 보관되어 있지 않습니다.", "この過去の実行の詳細なエラー情報は保持されていません。", "此历史执行的详细错误信息已不再保留。", "此歷史執行的詳細錯誤資訊已不再保留。", "Ya no se conserva el detalle del error de esta ejecución anterior.", "Le détail de l’erreur de cette ancienne exécution n’est plus conservé.", "Detaillierte Fehlerinformationen zu diesem früheren Lauf werden nicht mehr aufbewahrt.", "Os detalhes do erro desta execução anterior já não são conservados."],
  "problem.observed": ["Status checked {time}", "상태 점검 {time}", "状態確認 {time}", "状态确认于{time}", "狀態確認於{time}", "Estado comprobado {time}", "État vérifié {time}", "Status geprüft {time}", "Estado verificado {time}"],
  "problem.ackAt": ["Reviewed {time}", "확인 {time}", "確認済み {time}", "已查看 {time}", "已查看 {time}", "Revisado {time}", "Vérifié {time}", "Bestätigt {time}", "Revisto {time}"],
  "problem.liveNotice": ["This remains a problem until execution status is confirmed.", "실행 여부가 확인될 때까지 문제로 유지됩니다.", "実行状態が確認されるまで問題として表示します。", "确认执行状态前，此项将继续列为问题。", "確認執行狀態前，此項將繼續列為問題。", "Sigue siendo un problema hasta confirmar el estado de ejecución.", "Ce problème reste affiché jusqu’à confirmation de l’état d’exécution.", "Das Problem bleibt bestehen, bis der Ausführungsstatus bestätigt ist.", "Permanece um problema até o estado da execução ser confirmado."],
  "problem.empty": ["No problems need action.", "처리할 문제가 없습니다.", "対応が必要な問題はありません。", "没有待处理的问题。", "沒有待處理的問題。", "No hay problemas por resolver.", "Aucun problème à traiter.", "Keine Probleme mit Handlungsbedarf.", "Não há problemas por resolver."],
  "problem.emptyAcknowledged": ["No reviewed problems.", "확인한 문제 기록이 없습니다.", "確認済みの問題はありません。", "没有已查看的问题记录。", "沒有已查看的問題記錄。", "No hay problemas revisados.", "Aucun problème vérifié.", "Keine bestätigten Probleme.", "Não há problemas revistos."],
  "problem.previous": ["Previous", "이전", "前へ", "上一页", "上一頁", "Anterior", "Précédent", "Zurück", "Anterior"],
  "problem.next": ["Next", "다음", "次へ", "下一页", "下一頁", "Siguiente", "Suivant", "Weiter", "Seguinte"],
  "problem.stopConfirm": ["Stop {count} connected executions? File changes will not be reverted.", "연결된 실행 {count}개를 중단할까요? 파일 변경사항은 되돌리지 않습니다.", "接続された{count}件の実行を停止しますか？ファイルの変更は元に戻りません。", "停止{count}个关联执行？文件修改不会撤销。", "停止{count}個關聯執行？檔案修改不會撤銷。", "¿Detener {count} ejecuciones conectadas? Los cambios en archivos no se revierten.", "Arrêter {count} exécutions liées ? Les modifications des fichiers seront conservées.", "{count} verbundene Ausführungen stoppen? Dateiänderungen werden nicht rückgängig gemacht.", "Parar {count} execuções ligadas? As alterações nos ficheiros não serão revertidas."],
  "problem.changed": ["The problem list or execution state changed. Select the refreshed entries again.", "문제 목록이나 실행 상태가 변경되었습니다. 갱신된 항목을 다시 선택해 주세요.", "問題一覧または実行状態が変わりました。更新された項目を再選択してください。", "问题列表或执行状态已更改，请重新选择更新后的条目。", "問題清單或執行狀態已變更，請重新選擇更新後的項目。", "Cambió la lista o el estado de ejecución. Vuelve a seleccionar las entradas actualizadas.", "La liste ou l’état d’exécution a changé. Sélectionnez à nouveau les éléments actualisés.", "Die Problemliste oder der Ausführungsstatus hat sich geändert. Wählen Sie die aktualisierten Einträge erneut aus.", "A lista ou o estado da execução mudou. Selecione novamente as entradas atualizadas."],
  "problem.inspectPending": ["Status inspection is in progress. Check again shortly.", "상태 점검이 진행 중입니다. 잠시 후 다시 확인해 주세요.", "状態を確認中です。しばらくしてから再確認してください。", "正在检查状态，请稍后再次确认。", "正在檢查狀態，請稍後再次確認。", "Se está comprobando el estado. Vuelve a comprobarlo en breve.", "La vérification est en cours. Réessayez dans un instant.", "Der Status wird geprüft. Prüfen Sie gleich noch einmal.", "A verificação está em curso. Verifique novamente em breve."],
  "problem.rechecked": ["Status checked again. Remaining problems need further action.", "상태를 다시 확인했습니다. 남아 있는 문제는 추가 조치가 필요합니다.", "状態を再確認しました。残っている問題には追加対応が必要です。", "已重新确认状态，剩余问题需要进一步处理。", "已重新確認狀態，剩餘問題需要進一步處理。", "Estado comprobado de nuevo. Los problemas restantes necesitan más acciones.", "État revérifié. Les problèmes restants nécessitent une intervention.", "Status erneut geprüft. Verbleibende Probleme erfordern weitere Maßnahmen.", "Estado verificado novamente. Os problemas restantes requerem mais ações."],
  "problem.ackDone": ["Reviewed {count} finished failures.", "종료된 실패 {count}건을 확인 처리했습니다.", "終了済みの失敗{count}件を確認しました。", "已查看{count}个已结束的失败。", "已查看{count}個已結束的失敗。", "Se revisaron {count} fallos finalizados.", "{count} échecs terminés ont été vérifiés.", "{count} beendete Fehler bestätigt.", "Foram revistas {count} falhas terminadas."],
  "problem.historyNotice": ["Problems remain available for review throughout the retention period. Reviewing preserves the failed outcome. Active work and undelivered results are protected; Codex conversations and project files are kept.", "문제는 보관 기간 동안 확인할 수 있습니다. 확인함을 눌러도 실패 결과는 유지됩니다. 진행 중인 작업과 미전달 결과는 보존하며, Codex 대화와 프로젝트 파일은 유지됩니다.", "問題は保持期間中に確認できます。確認しても失敗の結果は変わりません。進行中の作業、未配信の結果、Codexの会話とプロジェクトファイルは保持されます。", "保留期限内可查看问题。标记已查看不会更改失败结果。正在进行的工作、未送达的结果、Codex对话和项目文件将保留。", "保留期限內可查看問題。標記已查看不會變更失敗結果。進行中的工作、未送達的結果、Codex對話和專案檔案將保留。", "Los problemas se pueden revisar durante el periodo de conservación. Revisarlos mantiene el resultado fallido. Se conservan el trabajo activo, los resultados sin entregar, las conversaciones de Codex y los archivos del proyecto.", "Les problèmes restent consultables pendant la durée de conservation. Leur vérification conserve le résultat d’échec. Le travail actif, les résultats non remis, les conversations Codex et les fichiers du projet sont conservés.", "Probleme können während der Aufbewahrungsdauer geprüft werden. Die Bestätigung ändert das Fehlerergebnis nicht. Aktive Arbeit, nicht zugestellte Ergebnisse, Codex-Gespräche und Projektdateien bleiben erhalten.", "Os problemas podem ser revistos durante o período de retenção. A revisão mantém o resultado de falha. O trabalho ativo, os resultados não entregues, as conversas do Codex e os ficheiros do projeto são conservados."]
} as const;

const locales = ["en","ko","ja","zh-Hans","zh-Hant","es","fr","de","pt"] as const;
export const PROBLEM_REVIEW_TRANSLATIONS = Object.fromEntries(locales.map((locale,index) => [locale,
  Object.fromEntries(Object.entries(COPY).map(([key,values]) => [key,values[index]]))
])) as Record<(typeof locales)[number],Record<keyof typeof COPY,string>>;
