/**
 * Generated by `npm run release:sync` from the final self-contained card HTML.
 * Do not edit this file by hand.
 */
export const UI_RESOURCE_MANIFEST = {
  "manifestVersion": 2,
  "strategy": "content-hash",
  "hashAlgorithm": "sha256",
  "hashLength": 12,
  "minimumContractGeneration": {
    "settings": 9,
    "activity": 12,
    "dashboard": 6,
    "question": 1
  },
  "releaseInventory": {
    "catalog": "ui-release-catalog.json",
    "catalogSha256": "8e2031a2489994ab5702c5e3f94d5439c7fa78e164fe1e8774b979c71af3fd11",
    "activeResources": [
      "settings",
      "activity",
      "dashboard",
      "question"
    ],
    "compatibilityResources": [],
    "retirement": {
      "activity": {
        "lifecycle": "historical-revisions-retired",
        "newPresentations": true,
        "replacement": "current-resource",
        "firstStableWithReplacement": "0.4.1",
        "minimumSupportRule": "none",
        "statePreserved": [
          "activities",
          "agents",
          "jobs",
          "questions",
          "results",
          "idempotency"
        ]
      }
    },
    "selected": [
      {
        "name": "settings",
        "digest": "52c19aebb4e92933142fe0b7edbfa8dce0bcf8b3c2bce4e9284680a3ebf205bc",
        "uri": "ui://codex-mcp-bridge/settings/52c19aebb4e9.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_settings",
        "requiredTools": [
          "codex_settings",
          "codex_ui_read",
          "codex_update_settings"
        ]
      },
      {
        "name": "activity",
        "digest": "bc75a45e487545ba09982494854f220fb68dff7b437dcc2407902b60d5003a16",
        "uri": "ui://codex-mcp-bridge/activity/bc75a45e4875.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_activity",
        "requiredTools": [
          "codex_activity",
          "codex_activity_rehydrate",
          "codex_activity_snapshot",
          "codex_activity_handoff",
          "codex_activity_job_cancel",
          "codex_background_process_terminate",
          "codex_interaction_respond",
          "codex_job_steer"
        ]
      },
      {
        "name": "dashboard",
        "digest": "86e53748068a0db81c36909a8ced64bd19d84bd705bc0fd1fdce417e77dc621c",
        "uri": "ui://codex-mcp-bridge/dashboard/86e53748068a.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_dashboard",
        "requiredTools": [
          "codex_dashboard",
          "codex_ui_history",
          "codex_ui_problem",
          "codex_ui_read"
        ]
      },
      {
        "name": "question",
        "digest": "a93cf2f84a75b0927ac228363e165b08a3b35cbfffc002397b4ce38f0d6f5c9d",
        "uri": "ui://codex-mcp-bridge/question/a93cf2f84a75.html",
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_ask_user",
        "requiredTools": [
          "codex_ask_user",
          "codex_question_action",
          "codex_ui_read"
        ]
      }
    ]
  },
  "resources": {
    "settings": {
      "digest": "52c19aebb4e92933142fe0b7edbfa8dce0bcf8b3c2bce4e9284680a3ebf205bc",
      "uri": "ui://codex-mcp-bridge/settings/52c19aebb4e9.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Settings",
          "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": false,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, Fast mode, Codex-app thread visibility, interface-language, concurrency for Codex MCP Bridge for ChatGPT.",
          "openai/widgetPrefersBorder": false,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 21
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_settings",
        "requiredTools": [
          "codex_settings",
          "codex_ui_read",
          "codex_update_settings"
        ]
      },
      "previous": []
    },
    "activity": {
      "digest": "bc75a45e487545ba09982494854f220fb68dff7b437dcc2407902b60d5003a16",
      "uri": "ui://codex-mcp-bridge/activity/bc75a45e4875.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Activity Feed",
          "description": "Localized compact current-work summary with an explicit paginated Activity history view.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Shows current Codex work compactly and opens paginated scoped Activity history on explicit request.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 30
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_activity",
        "requiredTools": [
          "codex_activity",
          "codex_activity_rehydrate",
          "codex_activity_snapshot",
          "codex_activity_handoff",
          "codex_activity_job_cancel",
          "codex_background_process_terminate",
          "codex_interaction_respond",
          "codex_job_steer"
        ]
      },
      "previous": []
    },
    "dashboard": {
      "digest": "86e53748068a0db81c36909a8ced64bd19d84bd705bc0fd1fdce417e77dc621c",
      "uri": "ui://codex-mcp-bridge/dashboard/86e53748068a.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Codex Status",
          "description": "Codex status card with conversation-first defaults, an all-conversations view, nested Agents, retained turn history, and validated request review.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": false,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Shows Codex work and history from this conversation when records exist, otherwise all conversations. Switch scope at the top; both views use the same execution states and approval/input request review.",
          "openai/widgetPrefersBorder": false,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": [],
            "redirect_domains": [
              "https://chatgpt.com"
            ]
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 29
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_dashboard",
        "requiredTools": [
          "codex_dashboard",
          "codex_ui_history",
          "codex_ui_problem",
          "codex_ui_read"
        ]
      },
      "previous": []
    },
    "question": {
      "digest": "a93cf2f84a75b0927ac228363e165b08a3b35cbfffc002397b4ce38f0d6f5c9d",
      "uri": "ui://codex-mcp-bridge/question/a93cf2f84a75.html",
      "metadata": {
        "descriptor": {
          "title": "Your input",
          "description": "Questions written by GPT for the user; answers return to GPT.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Collects the user's answers for GPT without directly answering or approving Codex requests.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 1
        }
      },
      "releaseProvenance": {
        "inventories": [
          "development-current"
        ],
        "sourceIds": [
          "rendered-current"
        ],
        "presenterTool": "codex_ask_user",
        "requiredTools": [
          "codex_ask_user",
          "codex_question_action",
          "codex_ui_read"
        ]
      },
      "previous": []
    }
  }
} as const;

export type UiResourceName = keyof typeof UI_RESOURCE_MANIFEST.resources;
