/**
 * Generated by `npm run release:sync` from the final self-contained card HTML.
 * Do not edit this file by hand.
 */
export const UI_RESOURCE_MANIFEST = {
  "manifestVersion": 1,
  "strategy": "content-hash",
  "hashAlgorithm": "sha256",
  "hashLength": 12,
  "minimumContractGeneration": {
    "settings": 9,
    "activity": 11
  },
  "resources": {
    "settings": {
      "digest": "c0afef77c90b91b31d324cc9ddcdd0cc9f5c1868b9bbb5ab64a63617910a5b83",
      "uri": "ui://codex-mcp-bridge/settings/c0afef77c90b.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Settings",
          "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 9
        }
      },
      "previous": [
        {
          "digest": "7c3ab734ff3a456fa7809107cfe82b9e6e751aefd2d3284c3f838cba7b35cc2a",
          "uri": "ui://codex-mcp-bridge/settings/7c3ab734ff3a.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "34e2eb4c94d2641aef4f7a4732dd839eac5b24bc37f6218958041929cdbdc38f",
          "uri": "ui://codex-mcp-bridge/settings/34e2eb4c94d2.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "2350e96e107c9ea2ef396200c7a13685c0587523973b7f83097f529e875195ea",
          "uri": "ui://codex-mcp-bridge/settings/2350e96e107c.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "89f54072f7455b92676fd3f627b75c9f059381373169ce596d6ba173ae5f74de",
          "uri": "ui://codex-mcp-bridge/settings/89f54072f745.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "ad2c5a241a90fa8f9a5e9c3ffdb4ae6cd105376fdf13211733ec36ba9da731b6",
          "uri": "ui://codex-mcp-bridge/settings/ad2c5a241a90.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "ad24ba83c6937a38db7c696a507b6ce166a2176705c93d5d8d2faae78104e124",
          "uri": "ui://codex-mcp-bridge/settings/ad24ba83c693.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, Codex-app thread visibility, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        }
      ]
    },
    "activity": {
      "digest": "e381833d1c75bcb0edbe1de3529b9ce3b7f95e251407295609cd90ed7bed7885",
      "uri": "ui://codex-mcp-bridge/activity/e381833d1c75.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Activity Feed",
          "description": "Localized flat feed with current or latest Codex model and effort selections.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 11
        }
      },
      "previous": [
        {
          "digest": "5e4acb22f165f3e6e3e66c571cb5e7fa1cd9536084d4cebc92237e54114d78b3",
          "uri": "ui://codex-mcp-bridge/activity/5e4acb22f165.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 11
            }
          }
        },
        {
          "digest": "c3c3c87be464fe6d5c75658deb5f0b33d597070f7c3c0e600741c3a69360ca76",
          "uri": "ui://codex-mcp-bridge/activity/c3c3c87be464.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 11
            }
          }
        },
        {
          "digest": "17c24231c5538afd2160ef4703100eabb8c22aa0fe278b932a681cca283c0194",
          "uri": "ui://codex-mcp-bridge/activity/17c24231c553.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 11
            }
          }
        },
        {
          "digest": "b4725cb7de0b5b7b0d8b1d0ea8ffe483318f0e2b47d26cc24d8c24347aefee5c",
          "uri": "ui://codex-mcp-bridge/activity/b4725cb7de0b.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "17be799a4a656bd5311f13baaec3a762dfe0bfb9a7060fd15eb38e30178e94af",
          "uri": "ui://codex-mcp-bridge/activity/17be799a4a65.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "8f9b0c10e534f0999323924f3b26183d9d2fe0a0c6f52db1f4328922346d57c1",
          "uri": "ui://codex-mcp-bridge/activity/8f9b0c10e534.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "d7d73c496d9b4a87b19c6977d6c7e327689aa2644df6677e65543e83c73bf8a1",
          "uri": "ui://codex-mcp-bridge/activity/d7d73c496d9b.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "5804dd38e35a65d6d133a2e8bdb28f28aab85b4d5bc8ace08f45fad798ed86a2",
          "uri": "ui://codex-mcp-bridge/activity/5804dd38e35a.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "536d28d41856718efa9be2ca713ad2cc1f044e6b4cdbe05d4d34f80d8a62d755",
          "uri": "ui://codex-mcp-bridge/activity/536d28d41856.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 10
            }
          }
        },
        {
          "digest": "4a8f190de901e8426ea300265ddbe749dbbc7fd19573e4c17821c907b0753ef1",
          "uri": "ui://codex-mcp-bridge/activity/4a8f190de901.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 7
            }
          }
        },
        {
          "digest": "030f9817fd9ed8ee148e78a000debf573f84a8690142d6ac0aa9770df8ebc476",
          "uri": "ui://codex-mcp-bridge/activity/030f9817fd9e.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 9
            }
          }
        },
        {
          "digest": "c06844041247d1650e6b5645fadbf4a0c6d30b24c1797373a0f3a831090db85d",
          "uri": "ui://codex-mcp-bridge/activity/c06844041247.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 8
            }
          }
        },
        {
          "digest": "ec8bc991267df01729e77d2eb51ce2cb1f6e1ae79b7903278679ca20a2ecd855",
          "uri": "ui://codex-mcp-bridge/activity/ec8bc991267d.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 7
            }
          }
        },
        {
          "digest": "24b062eaa3373b8dd46bfe09a3210e5c8e2e676c23dc669d88f10806547137c1",
          "uri": "ui://codex-mcp-bridge/activity/24b062eaa337.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 7
            }
          }
        }
      ]
    }
  }
} as const;

export type UiResourceName = keyof typeof UI_RESOURCE_MANIFEST.resources;
