/**
 * Generated by `npm run release:sync` from the final self-contained card HTML.
 * Do not edit this file by hand.
 */
export const UI_RESOURCE_MANIFEST = {
  "manifestVersion": 1,
  "strategy": "content-hash",
  "hashAlgorithm": "sha256",
  "hashLength": 12,
  "retainPrevious": 1,
  "resources": {
    "settings": {
      "digest": "5fd94685e0708f71bdc678bc88e6f0216a477449c8442afabb396648c359d264",
      "uri": "ui://codex-mcp-bridge/settings/5fd94685e070.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Settings",
          "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 5
        }
      },
      "previous": [
        {
          "digest": "ee7d1ab2163eba701352a52d559e41198e4fb9f1af9f38bb2f45d49014a90279",
          "uri": "ui://codex-mcp-bridge/settings/ee7d1ab2163e.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Settings",
              "description": "Localized interactive settings card for user-configurable Codex bridge preferences.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Configure named projects, saved access, model/effort policy, independent Priority processing, interface-language, concurrency, and Activity-card visibility for Codex MCP Bridge for ChatGPT.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 4
            }
          }
        }
      ]
    },
    "activity": {
      "digest": "bdc1b6148bc3db3ff48c80005f27c4f2aef55c59a53f5f7fe5d92e4debebaed8",
      "uri": "ui://codex-mcp-bridge/activity/bdc1b6148bc3.html",
      "metadata": {
        "descriptor": {
          "title": "Codex MCP Bridge for ChatGPT Activity Feed",
          "description": "Localized flat feed with current or latest Codex model and effort selections.",
          "mimeType": "text/html;profile=mcp-app"
        },
        "content": {
          "ui": {
            "prefersBorder": true,
            "csp": {
              "connectDomains": [],
              "resourceDomains": []
            },
            "domain": "https://web-sandbox.oaiusercontent.com"
          },
          "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
          "openai/widgetPrefersBorder": true,
          "openai/widgetCSP": {
            "connect_domains": [],
            "resource_domains": []
          },
          "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
          "codex/uiContractGeneration": 4
        }
      },
      "previous": [
        {
          "digest": "0012c27272a00a5bb7ff93b1de7942f35ea7f622d1282d1d8f8a05a5e565bc2c",
          "uri": "ui://codex-mcp-bridge/activity/0012c27272a0.html",
          "metadata": {
            "descriptor": {
              "title": "Codex MCP Bridge for ChatGPT Activity Feed",
              "description": "Localized flat feed with current or latest Codex model and effort selections.",
              "mimeType": "text/html;profile=mcp-app"
            },
            "content": {
              "ui": {
                "prefersBorder": true,
                "csp": {
                  "connectDomains": [],
                  "resourceDomains": []
                },
                "domain": "https://web-sandbox.oaiusercontent.com"
              },
              "openai/widgetDescription": "Shows Codex work and each Agent's current or latest model and effort selection as a flat feed.",
              "openai/widgetPrefersBorder": true,
              "openai/widgetCSP": {
                "connect_domains": [],
                "resource_domains": []
              },
              "openai/widgetDomain": "https://web-sandbox.oaiusercontent.com",
              "codex/uiContractGeneration": 4
            }
          }
        }
      ]
    }
  }
} as const;

export type UiResourceName = keyof typeof UI_RESOURCE_MANIFEST.resources;
